sudo: required
language: java

os:
  - linux
#  - osx 

services:
  - docker

before_install:
  - cd rabix-integration-testing
  - git clone https://github.com/common-workflow-language/common-workflow-language.git
  - cd common-workflow-language
  - ls -ltra
  - git status
  - git fetch
  - git pull
  - git status
  - cd ..
  - cd ..
  - touch /home/travis/build/markosbg/debug/rabix-integration-testing/common-workflow-language/draft-2/errorConf.log

script:
  - mvn clean install package -P all
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -e -X

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - marko.vukobrat@sbgenomics.com
      - janko.simonovic@sbgenomics.com
      - sinisa.ivkovic@sbgenomics.com
    on_success: always
    on_failure: always
