sudo: required
language: java
 
services:
  - docker

before_install:
  - cd rabix-integration-testing
  - git clone https://github.com/rabix/common-workflow-language.git
  - cd ..

script:
  - mvn clean install package -P draft-sb
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -Dexec.args="draft-sb" -e -X
  - mvn clean install package -P draft-1
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -Dexec.args="draft-1" -e -X
  - mvn clean install package -P draft-2
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -Dexec.args="draft-2" -e -X
  - mvn clean install package -P draft-3
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -Dexec.args="draft-3" -e -X
  - mvn clean install package -P cwl
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -Dexec.args="cwl" -e -X

 

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - marko.vukobrat@sbgenomics.com
    on_success: always
    on_failure: always
